[package]
name = "triodion-macros"
description = "triodion-macros is a procedural macro used for defining datasets"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "triodion_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
indexmap = { workspace = true }
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lints]
workspace = true
